name: Build release and Push to Github Packages

on:
  push:
    branches: [ "release" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: 'master' #V1_6_6

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Maven
        run: mvn -B clean package -pl :pljava-api

      - name: Push artefact to Github Packages
        run: mvn -B deploy -DaltDeploymentRepository=githublatlon::default::https://maven.pkg.github.com/lat-lon/pljava
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
